dns:
  upstream_dns:
    - '#cloudflare'
    - https://cloudflare-dns.com/dns-query
    - '#tls://1.1.1.1'
    - '#tls://1.0.0.1'
    - '#google'
    - '#https://dns.google/dns-query'
    - '#tls://dns.google'
    - '#tls://8.8.8.8'
    - '#tls://8.8.4.4'
    - '#Quad9'
    - https://dns.quad9.net/dns-query
    - '#tls://dns.quad9.net'
    - '#tls://9.9.9.9'
    - '#tls://149.112.112.112'
    - '#Yandex'
    - https://common.dot.dns.yandex.net/dns-query
    - '#tls://common.dot.dns.yandex.net'
    - '#tls://77.88.8.8'
    - '#tls://77.88.8.1'
    - '#AdGuard'
    - https://dns.adguard-dns.com/dns-query
    - '#https://unfiltered.adguard-dns.com/dns-query'
    - '#tls://dns.adguard-dns.com'
    - '#tls://unfiltered.adguard-dns.com'
    - '#tls://94.140.14.14'
    - '#tls://94.140.15.15'
    - '#Comss.one'
    - https://dns.comss.one/dns-query
    - '#tls://dns.comss.one'
    - '#OpenDNS'
    - https://doh.opendns.com/dns-query
    - '#tls://dns.opendns.com'
    - '#tls://208.67.222.222'
    - '#tls://208.67.220.220'
    - '#Mullvad'
    - '#https://dns.mullvad.net/dns-query'
    - '#tls://dns.mullvad.net'
    - '#themoviedb.org domain bypass'
    - '[/themoviedb.org/]https://dns10.quad9.net/dns-query'
    - '#tmdb.org domain bypass'
    - '[/tmdb.org/]https://dns10.quad9.net/dns-query'
    - '[/image.tmdb.org/]https://dns10.quad9.net/dns-query'
  local_ptr_upstreams:
    - 172.17.0.1
    - 172.18.0.1
    - 172.20.0.1
    - 172.21.0.1
    - 172.22.0.1
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: https://someonewhocares.org/hosts/zero/hosts
    name: Dan Pollock's List
    id: 1645953624
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
    name: Game Console Adblock List
    id: 1645953625
  - enabled: true
    url: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
    name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
    id: 1645953627
  - enabled: true
    url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
    name: Peter Lowe's List
    id: 1645953628
  - enabled: true
    url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
    name: Scam Blocklist by DurableNapkin
    id: 1645953630
  - enabled: true
    url: https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
    name: The Big List of Hacked Malware Web Sites
    id: 1645953631
  - enabled: true
    url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    name: NoCoin Filter List
    id: 1645953632
  - enabled: true
    url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    name: WindowsSpyBlocker - Hosts spy rules
    id: 1645953633
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareAdGuardHome.txt
    name: Dandelion Sprout's Anti-Malware List
    id: 1645953634
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
    name: Malicious URL Blocklist (URLHaus)
    id: 1690839331
user_rules:
  - '@@||static.lostfilm.top^$important'
  - '@@||static.lostfilm.tv^$important'
  - '@@||static.lostfilm.life^$important'
  - '@@||startup.mobile.yandex.net^$important'
  - '@@||arc.msn.com^$important'
  - '@@||metrics.icloud.com^$important'
  - '@@||g.live.com^$important'
  - '@@||log-upload-os.hoyoverse.com^$important'
filtering:
  rewrites:
    # null (16)
    - domain: terra.lan
      answer: terra.yaf.lan
      enabled: true
    - domain: mani.lan
      answer: mani.yaf.lan
      enabled: true
    - domain: luna.lan
      answer: luna.yaf.lan
      enabled: true
    - domain: selena.lan
      answer: selena.yaf.lan
      enabled: true
    - domain: hina.lan
      answer: hina.yaf.lan
      enabled: true
    - domain: phaeton.lan
      answer: phaeton.yaf.lan
      enabled: true
    - domain: moonadmin.lan
      answer: moonadmin.yaf.lan
      enabled: true
    - domain: moonmedia.lan
      answer: moonmedia.yaf.lan
      enabled: true
    - domain: moondns.lan
      answer: moondns.yaf.lan
      enabled: true
    - domain: moonproxy.lan
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: inky.lan
      answer: inky.yaf.lan
      enabled: true
    # vasilkovo (17)
    - domain: point.vas.wan
      answer: 192.168.1.1
      enabled: true
    - domain: yota.vas.wan
      answer: 192.168.8.1
      enabled: true
    - domain: router.vas.lan
      answer: ganymede.vas.lan
      enabled: true
    - domain: ganymede.vas.lan
      answer: 172.17.0.1
      enabled: true
    - domain: callisto.vas.lan
      answer: 172.17.0.2
      enabled: true
    - domain: himalia.vas.lan
      answer: 172.17.0.20
      enabled: true
    - domain: thebe.vas.lan
      answer: 172.17.0.21
      enabled: true
    - domain: amalthea.vas.lan
      answer: 172.17.0.4
      enabled: true
    - domain: '*.app.vas.lan'
      answer: io.vas.lan
      enabled: true
    - domain: io.vas.lan
      answer: 172.17.2.10
      enabled: true
    - domain: io.lan
      answer: io.vas.lan
      enabled: true
    - domain: '*.io.vas.lan'
      answer: io.vas.lan
      enabled: true
    - domain: europa.vas.lan
      answer: 172.17.2.11
      enabled: true
    - domain: europa.lan
      answer: europa.vas.lan
      enabled: true
    - domain: '*.europa.vas.lan'
      answer: europa.vas.lan
      enabled: true
    - domain: elara.vas.lan
      answer: 172.17.4.12
      enabled: true
    - domain: leda.yaf.lan
      answer: 172.17.4.110
      enabled: true
    - domain: ananke.yaf.lan
      answer: 172.17.4.11
      enabled: true
    # chanovo (18)
    - domain: router.cha.lan
      answer: titan.cha.lan
      enabled: true
    - domain: titan.cha.lan
      answer: 172.18.0.1
      enabled: true
    - domain: rhea.cha.lan
      answer: 172.18.0.2
      enabled: true
    - domain: dione.cha.lan
      answer: 172.18.0.3
      enabled: true
    - domain: '*.app.cha.lan'
      answer: mimas.cha.lan
      enabled: true
    - domain: mimas.cha.lan
      answer: 172.20.13.18
      enabled: true
    - domain: mimas.lan
      answer: mimas.cha.lan
      enabled: true
    - domain: '*.mimas.cha.lan'
      answer: mimas.cha.lan
      enabled: true
    # yasenevod (19)
    - domain: mts.yad.wan
      answer: 192.168.1.1
      enabled: true
    - domain: router.yad.lan
      answer: phobos.yad.lan
      enabled: true
    - domain: phobos.yad.lan
      answer: 172.21.0.1
      enabled: true
    # yasenevof (20)
    - domain: mts.yaf.wan
      answer: 192.168.1.1
      enabled: true
    - domain: yota.yaf.wan
      answer: 192.168.0.1
      enabled: true
    - domain: router.yaf.lan
      answer: titania.yaf.lan
      enabled: true
    - domain: titania.yaf.lan
      answer: 172.20.0.1
      enabled: true
    - domain: oberon.yaf.lan
      answer: 172.20.0.2
      enabled: true
    - domain: ariel.yaf.lan
      answer: 172.20.2.10
      enabled: true
    - domain: ariel.lan
      answer: ariel.yaf.lan
      enabled: true
    - domain: '*.ariel.yaf.lan'
      answer: ariel.yaf.lan
      enabled: true
    - domain: '*.app.yaf.lan'
      answer: ariel.yaf.lan
      enabled: true
    - domain: terra.yaf.lan
      answer: 172.20.2.12
      enabled: true
    - domain: '*.terra.yaf.lan'
      answer: terra.yaf.lan
      enabled: true
    - domain: mani.yaf.lan
      answer: 172.20.2.20
      enabled: true
    - domain: luna.yaf.lan
      answer: 172.20.2.21
      enabled: true
    - domain: '*.luna.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: selena.yaf.lan
      answer: 172.20.2.22
      enabled: true
    - domain: '*.selena.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: hina.yaf.lan
      answer: reserved
      enabled: false
    - domain: '*.hina.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: false
    - domain: moonadmin.yaf.lan
      answer: 172.20.2.210
      enabled: true
    - domain: '*.moonadmin.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: moonmedia.yaf.lan
      answer: 172.20.2.212
      enabled: true
    - domain: '*.moonmedia.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: moondns.yaf.lan
      answer: 172.20.2.250
      enabled: true
    - domain: '*.moondns.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: moonproxy.yaf.lan
      answer: 172.20.2.254
      enabled: true
    - domain: '*.moonproxy.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: phaeton.yaf.lan
      answer: 172.20.2.201
      enabled: true
    - domain: '*.appnul.yaf.lan'
      answer: moonproxy.yaf.lan
      enabled: true
    - domain: jupiter.yaf.lan
      answer: 172.20.4.10
      enabled: true
    - domain: mars.yaf.lan
      answer: 172.20.4.111
      enabled: true
    - domain: saturn.yaf.lan
      answer: 172.20.4.112
      enabled: true
    - domain: uranus.yaf.lan
      answer: 172.20.4.13
      enabled: true
    - domain: eris.yaf.lan
      answer: 172.20.4.14
      enabled: true
    - domain: leda.yaf.lan
      answer: 172.20.4.115
      enabled: true
    - domain: ananke.yaf.lan
      answer: 172.20.4.16
      enabled: true
    - domain: inky.yaf.lan
      answer: 172.20.6.50
      enabled: true
    # shodnenskaya4 (21)
    - domain: mts.sh4.wan
      answer: 192.168.1.1
      enabled: true
    - domain: router.sh4.lan
      answer: pluto.sh4.lan
      enabled: true
    - domain: pluto.sh4.lan
      answer: 172.21.1.1
      enabled: true
    - domain: pluto.lan
      answer: pluto.sh4.lan
      enabled: true
    - domain: '*.app.sh4.lan'
      answer: ixion.sh4.lan
      enabled: true
    - domain: ixion.sh4.lan
      answer: 172.21.2.10
      enabled: true
    - domain: ixion.lan
      answer: ixion.sh4.lan
      enabled: true
    - domain: '*.ixion.sh4.lan'
      answer: ixion.sh4.lan
      enabled: true
    # shodnenskaya5 (22)
    - domain: mts.sh5.wan
      answer: 192.168.1.1
      enabled: true
    - domain: router.sh5.lan
      answer: haumea.sh5.lan
      enabled: true
    - domain: haumea.sh5.lan
      answer: 172.22.0.1
      enabled: true
    - domain: '*.app.sh5.lan'
      answer: makemake.sh5.lan
      enabled: true
    - domain: makemake.sh5.lan
      answer: 172.22.2.10
      enabled: true
    - domain: makemake.lan
      answer: makemake.sh5.lan
      enabled: true
    - domain: '*.makemake.sh5.lan'
      answer: makemake.sh5.lan
      enabled: true
    # web
    - domain: proxima.web.wan
      answer: 208.92.227.11
      enabled: true
    - domain: proxima.wan
      answer: proxima.web.wan
      enabled: true
    - domain: adguard.app.web.wan
      answer: 172.29.172.100
      enabled: true
    - domain: share.app.web.wan
      answer: 172.29.172.101
      enabled: true
    - domain: webdav.app.web.wan
      answer: 172.29.172.102
      enabled: true