networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.13.0/24
          gateway: 198.19.13.1

volumes:
  radarr_config:
  sonarr_config:
  jackett_config:
  
services:
  radarr:
    container_name: mediarr-radarr
    hostname: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 31320:7878
    volumes:
      - radarr_config:/config
      - ${DATA_MOVIES}:/video/movies
      - ${DATA_ANIMATION}:/video/animation
      - ${DATA_DOWNLOAD}:/downloads
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK=002
    networks:
      net:
        ipv4_address: 198.19.13.2
    depends_on:
      jackett:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.13.2:7878"]
        interval: 30s
        timeout: 10s
        start_period: 10s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  sonarr:
    container_name: mediarr-sonarr    
    hostname: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 31330:8989
    volumes:
      - sonarr_config:/config
      - ${DATA_TVSHOWS}:/video/tvshows
      - ${DATA_ANIMATIONSHOWS}:/video/animationshows
      - ${DATA_DOCUMENTARY}:/video/documentary
      - ${DATA_DOWNLOAD}:/downloads
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
      - UMASK=002
    networks:
      net:
        ipv4_address: 198.19.13.3
    depends_on:
      jackett:
        condition: service_healthy
    healthcheck:
        test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.13.3:8989"]
        interval: 30s
        timeout: 10s
        start_period: 10s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped

  jackett:
    container_name: mediarr-jackett
    hostname: jackett
    image: lscr.io/linuxserver/jackett:latest
    ports:
      - 31340:9117
    volumes:
      - jackett_config:/config
      - /var/snap/docker/common/assets/mediarr/noname-clubl-rus.yml:/app/Jackett/Definitions/noname-clubl-rus.yml:ro
    environment:
      - PUID=1999
      - PGID=100
      - TZ=Europe/Moscow
    networks:
      net:
        ipv4_address: 198.19.13.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.13.4:9117"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
    depends_on:
      flaresolverr:
        condition: service_healthy

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: mediarr-flaresolverr
    hostname: flaresolverr
    networks:
      net:
        ipv4_address: 198.19.13.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.13.5:8191"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
