networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.4.0/24
          gateway: 198.19.4.1

volumes:
  config:
  icons:
  data:

services:  
  homarr:
    container_name: homarr
    hostname: homarr
    image: ghcr.io/ajnart/homarr:latest
    ports:
      - 30420:7575
    volumes:
      - config:/app/data/configs
      - icons:/app/public/icons
      - data:/data
      - /var/snap/docker/common/assets/homarr/wallpaper.jpeg:/app/public/imgs/wallpaper.jpeg:ro
    networks:
      net:
        ipv4_address: 198.19.4.2
    healthcheck:
        test: ["CMD", "wget", "--spider", "--timeout=10", "http://198.19.4.2:7575"]
        interval: 30s
        timeout: 10s
        start_period: 10s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped