all:
  children:

    linux:
      children:

        linux_server:
          children:

            linux_server_baremetal:
              children:

                linux_server_baremetal_master:
                  hosts:
                    io:
                    mimas:

                linux_server_baremetal_apprentice:
                  hosts:
                    europa:

                linux_server_baremetal_nas:
                  hosts:
                    terra:

                linux_server_baremetal_vmhost:
                  hosts:

            linux_server_virtual:
              hosts:
                phaeton:

        linux_workstation:
          children:

            linux_workstation_ultraLow:
              hosts:

            linux_workstation_low:
              hosts:

            linux_workstation_high:
              hosts:
