all:
  children:

    location:
      children:

        location_null:
          hosts:
            terra:
            phaeton:

        location_vasilkovo:
          hosts:
            io:
            europa:

        location_chanovo:
          hosts:
            mimas:

        location_yasenevod:
          hosts:

        location_yasenevof:
          hosts:

        location_shondenskaya4:
          hosts:

        location_shodnenskaya5:
          hosts:
