services:
  watchtower_remote3:
    container_name: watchtower_remote_${REMOTE3_NAME}
    image: nickfedor/watchtower
    volumes:
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 7 * * 6
      - WATCHTOWER_ROLLING_RESTART=true
      - DOCKER_HOST=${REMOTE3_URL}
    networks:
      net:
        ipv4_address: 198.19.8.3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: always