networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.7.0/24
          gateway: 198.19.7.1

volumes:
  config:
  sync:

services:
  resiliosync:
    container_name: resiliosync
    hostname: resiliosync
    image: lscr.io/linuxserver/resilio-sync:2.8.1
    environment:
      - PUID=1999
      - PGID=2000
      - UMASK=002
      - TZ=Europe/Moscow
    volumes:
      - config:/config
      - sync:/sync
      - ${DATA_DOCUMENTS_LESHA}:/sync/share/documents/users/lesha
      - ${DATA_SAVES}:/sync/share/saves
      - ${DATA_VIDEO_FAMILY}:/sync/share/video/family
      - ${DATA_VIDEO_PUBLIC}:/sync/share/video/public
      - ${DATA_PHOTO_LESHA}:/sync/share/photo/users/lesha
      - ${DATA_EXCHANGE}:/sync/exchange
    ports:
      - 30720:8888
      - 55555:55555
    networks:
      net:
        ipv4_address: 198.19.7.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://198.19.7.2:8888"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped
