networks:
  net:  
    ipam:
      config:
        - subnet: 198.19.14.0/24
          gateway: 198.19.14.1

volumes:
  data:

services:
  ollama-igpu:
    container_name: ollama-igpu
    hostname: ollama-igpu
    image: uberchuckie/ollama-intel-gpu
    volumes:
      - data:/root/.ollama
    environment:
      - TZ="Europe/Moscow"
      - OLLAMA_ORIGINS=*
      - DEVICE=Arc
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_NUM_CTX=4096
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 11434:11434
    networks:
      net:
        ipv4_address: 198.19.14.2
    healthcheck:
      test: ["CMD", "./ollama", "ps"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3    
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
    restart: unless-stopped